# Generated by Django 4.1.9 on 2023-06-12 03:08

import basic.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, unique=True)),
                ("price", models.IntegerField(default=0)),
                ("chat_history_limit", models.IntegerField(default=30)),
                ("emoji_publish_limit", models.IntegerField(default=10)),
                ("image_publish_limit", models.IntegerField(default=10)),
                ("daily_image_create_limit", models.IntegerField(default=20)),
                ("description", models.TextField(default="No Description")),
                ("private_message", models.BooleanField(default=True)),
                ("video_call", models.BooleanField(default=True)),
                ("audio_call", models.BooleanField(default=True)),
            ],
            bases=(models.Model, basic.models.AutoDate),
        ),
    ]
