# Generated by Django 4.1.9 on 2023-06-17 18:00

import basic.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(default="name", max_length=200)),
                ("count", models.IntegerField()),
            ],
            bases=(models.Model, basic.models.AutoDate),
        ),
    ]
