# Generated by Django 4.1.9 on 2023-06-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_avatar_url_alter_user_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="mail_verify",
            field=models.BooleanField(default=False),
        ),
    ]
